---
- hosts: all
  become: true
  become_method: sudo
  remote_user: user_name
  gather_facts: no

  tasks:
  - name: "Get user list from server"
    shell: "getent passwd {1000..60000} | awk -F ':' '{print $1}'"
    register: user_list
    tags: user_list_sts

  - debug:
      msg: "User list is: {{ item }}"
    with_items: "{{ user_list.stdout.split('\n') }}"
    tags: user_list_sts

  - name: "Check user password status"
    shell: "chage -l {{ item }} | head -n1 | awk -F ':' '{print $2}' | sed 's/,//g' | sed 's/\ /_/g' |  sed 's/^_//g'"
    with_items: "{{ user_list.stdout.split('\n') }}"
    register: user_password
    tags: user_password_sts

  - debug:
      msg: "password change status for {{ item.cmd.split('|')[0].replace('chage -l ', '') }}user is : {{ item.stdout }}"
    with_items: "{{ user_password.results }}"
    loop_control:
      label: "{{ item.stdout }}"
    tags: user_password_sts
