---
- hosts: all
  become: true
  become_method: sudo
  remote_user: onmoawxuser
  gather_facts: no

  tasks:
  - name: "Updating grub conf file"
    lineinfile:
      path: "/var/tmp/grub_file.txt"
      backrefs: true
      regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT=.*")$'
      state: present
      line: '\1 numa_balancing=disable'
